In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
import json
import shutil
import csv
import ast

In [2]:
x=pd.read_json ('cinema.json')
#x.to_csv('cinemadata.csv') 
x

,Capacity,DaysShowedInWeek,Index,LastDate,Lifetime,Movie,OccAtWeek,OccPer,OtherReleasesInWeek,ReleaseDate,ShowsInWeek,WeeksSinceRelease
0,3100,5,0,2015-12-17,2,0001000001,2494,0.804516,8,2015-12-04,10,0
1,3390,7,1,2015-12-17,2,0001000001,1932,0.569912,4,2015-12-04,14,1
2,860,2,2,2015-12-17,2,0001000001,222,0.258140,4,2015-12-04,4,2
3,110,1,3,2016-01-06,5,0001000002,59,0.536364,8,2015-12-04,1,0
4,720,6,4,2016-01-06,5,0001000002,630,0.875000,7,2015-12-04,6,3
5,1320,7,5,2016-01-06,5,0001000002,980,0.742424,7,2015-12-04,11,4
6,120,1,6,2016-01-06,5,0001000002,34,0.283333,6,2015-12-04,1,5
7,2630,5,7,2016-01-13,6,0001000003,1725,0.655894,8,2015-12-04,14,0
8,4590,7,8,2016-01-13,6,0001000003,3479,0.757952,4,2015-12-04,28,1
9,1955,7,9,2016-01-13,6,0001000003,1230,0.629156,4,2015-12-04,13,2
10,1048,7,10,2016-01-13,6,0001000003,798,0.761450,7,2015-12-04,8,3
11,1847,7,11,2016-01-13,6,0001000003,1116,0.604223,7,2015-12-04,10,4
12,1102,7,12,2016-01-13,6,0001000003,853,0.774047,6,2015-12-04,9,5
13,120,1,13,2016-01-13,6,0001000003,96,0.800000,11,2015-12-04,1,6
14,2860,5,14,2016-01-13,6,0001000004,1540,0.538462,8,2015-12-04,15,0
15,3349,7,15,2016-01-13,6,0001000004,2369,0.707375,4,2015-12-04,16,1
16,1537,7,16,2016-01-13,6,0001000004,961,0.625244,4,2015-12-04,9,2
17,1397,7,17,2016-01-13,6,0001000004,851,0.609162,7,2015-12-04,11,3
18,862,7,18,2016-01-13,6,0001000004,645,0.748260,7,2015-12-04,7,4
19,895,7,19,2016-01-13,6,0001000004,643,0.718436,6,2015-12-04,7,5
20,131,1,20,2016-01-13,6,0001000004,99,0.755725,11,2015-12-04,1,6
21,440,4,21,2015-12-23,3,0001000005,335,0.761364,8,2015-12-04,4,0
22,1040,7,22,2015-12-23,3,0001000005,926,0.890385,4,2015-12-04,9,1
23,890,7,23,2015-12-23,3,0001000005,671,0.753933,4,2015-12-04,8,2
24,110,1,24,2015-12-23,3,0001000005,101,0.918182,7,2015-12-04,1,3
25,110,1,25,2015-12-04,0,0001000006,41,0.372727,8,2015-12-04,1,0
26,600,5,26,2015-12-10,1,0001000007,242,0.403333,8,2015-12-04,5,0
27,240,2,27,2015-12-10,1,0001000007,51,0.212500,4,2015-12-04,2,1
28,1260,5,28,2015-12-17,2,0001000008,1136,0.901587,8,2015-12-04,11,0
29,1680,7,29,2015-12-17,2,0001000008,1366,0.813095,4,2015-12-04,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3480,660,6,3480,2017-11-16,2,HO00002155,503,0.762121,9,2017-11-03,6,1
3481,220,2,3481,2017-11-16,2,HO00002155,212,0.963636,7,2017-11-03,2,2
3482,262,2,3482,2017-11-16,2,HO00002156,61,0.232824,11,2017-11-06,2,0
3483,791,7,3483,2017-11-16,2,HO00002156,496,0.627054,9,2017-11-06,7,1
3484,220,2,3484,2017-11-16,2,HO00002156,99,0.450000,7,2017-11-06,2,2
3485,550,5,3485,2017-11-09,1,HO00002163,420,0.763636,11,2017-11-03,5,0
3486,220,2,3486,2017-11-09,1,HO00002163,140,0.636364,9,2017-11-03,2,1
3487,550,5,3487,2017-11-09,1,HO00002164,385,0.700000,11,2017-11-03,5,0
3488,220,2,3488,2017-11-09,1,HO00002164,124,0.563636,9,2017-11-03,2,1
3489,110,1,3489,2017-11-08,0,HO00002167,93,0.845455,9,2017-11-08,1,0
3490,5302,6,3490,2017-11-18,1,HO00002168,3540,0.667673,9,2017-11-09,26,0
3491,1920,4,3491,2017-11-18,1,HO00002168,905,0.471354,7,2017-11-09,12,1
3492,2270,5,3492,2017-11-18,1,HO00002169,2009,0.885022,9,2017-11-10,17,0
3493,1660,4,3493,2017-11-18,1,HO00002169,1515,0.912651,7,2017-11-10,13,1
3494,1440,5,3494,2017-11-18,1,HO00002170,1357,0.942361,9,2017-11-10,12,0
3495,910,4,3495,2017-11-18,1,HO00002170,838,0.920879,7,2017-11-10,8,1
3496,655,5,3496,2017-11-18,1,HO00002171,522,0.796947,9,2017-11-10,5,0
3497,524,4,3497,2017-11-18,1,HO00002171,397,0.757634,7,2017-11-10,4,1
3498,1100,5,3498,2017-11-16,1,HO00002172,775,0.704545,9,2017-11-10,10,0
3499,220,2,3499,2017-11-16,1,HO00002172,121,0.550000,7,2017-11-10,2,1
3500,917,5,3500,2017-11-16,1,HO00002173,545,0.594329,9,2017-11-10,7,0
3501,262,2,3501,2017-11-16,1,HO00002173,98,0.374046,7,2017-11-10,2,1
3502,600,5,3502,2017-11-16,1,HO00002174,532,0.886667,9,2017-11-10,5,0
3503,240,2,3503,2017-11-16,1,HO00002174,155,0.645833,7,2017-11-10,2,1
3504,440,4,3504,2017-11-13,0,HO00002175,228,0.518182,9,2017-11-10,4,0
3505,120,1,3505,2017-11-15,0,HO00002188,112,0.933333,7,2017-11-15,1,0
3506,2410,2,3506,2017-11-18,0,HO00002193,2318,0.961826,7,2017-11-17,9,0
3507,330,2,3507,2017-11-18,0,HO00002196,255,0.772727,7,2017-11-17,3,0
3508,360,2,3508,2017-11-18,0,HO00002197,304,0.844444,7,2017-11-17,3,0
3509,220,2,3509,2017-11-18,0,HO00002198,162,0.736364,7,2017-11-17,2,0

In [9]:
#making directories for positive and negative
import os
dir = os.path.join("Assignment_1_a/positive")
if not os.path.exists(dir):
    os.mkdir(dir)
    
dir = os.path.join("Assignment_1_a/negative")
if not os.path.exists(dir):
    os.mkdir(dir)

In [36]:
#copying the positive reviews
with open('Assignment_1_a/Positive_Reviews.txt', 'r') as f:
    mylist = ast.literal_eval(f.read())
    for i in mylist:
        source ='Assignment_1_a/Reviews/'+i
        des = 'Assignment_1_a/positive'
        shutil.copy(source, des)

In [37]:
with open('Assignment_1_a/Negative_Reviews.txt', 'r') as f1:
    mylist = ast.literal_eval(f1.read())
    for i in mylist:
        source = 'Assignment_1_a/Reviews/'+i
        des ='Assignment_1_a/negative'
        shutil.copy(source, des)

In [3]:
df = pd.read_csv('Assignment_1_a/Reviews/cv000_29590.txt')
df.to_csv('Assignment_1_a/Reviews/cv000_29590.csv')

In [5]:
txt_file = r"Assignment_1_a/Reviews/cv000_29590.txt"
csv_file = r"Assignment_1_a/Reviews/cv000_29590.csv"

In [6]:
with open(txt_file, 'r') as infile, open(csv_file, 'w') as outfile:
    stripped = (line.strip() for line in infile)
    lines = (line.split(" ") for line in stripped if line)
    writer = csv.writer(outfile)
    writer.writerows(lines)

In [7]:
df = pd.read_csv('Assignment_1_a/Reviews/cv000_29590.csv',error_bad_lines=False)

b'Skipping line 37: expected 52 fields, saw 76\n'

In [8]:
df

,films,adapted,from,comic,books,have,had,plenty,of,success,...,really,been,a,comic.1,book,like,from.1,hell,before,.
0,for,starters,",",it,was,created,by,alan,moore,(,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,to,say,moore,and,campbell,thoroughly,researched,the,subject,of,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,the,book,(,or,"""",graphic,novel,",","""",if,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,in,other,words,",",don't,dismiss,this,film,because,of,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,if,you,can,get,past,the,whole,comic,book,thing,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,getting,the,hughes,brothers,to,direct,this,seems,almost,as,...,crime,than,the,mad,geniuses,behind,menace,ii,society,?
6,the,ghetto,in,question,is,",",of,course,",",whitechapel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,it's,a,filthy,",",sooty,place,where,the,whores,(,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,when,the,first,stiff,turns,up,",",copper,peter,godley,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,abberline,",",a,widower,",",has,prophetic,dreams,he,unsuccessfully,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,upon,arriving,in,whitechapel,",",he,befriends,an,unfortunate,named,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,i,don't,think,anyone,needs,to,be,briefed,on,jack,...,and,the,reasons,he,chooses,to,slay,.,NaN,NaN
12,in,the,comic,",",they,don't,bother,cloaking,the,identity,...,the,very,end,.,NaN,NaN,NaN,NaN,NaN,NaN
13,it's,funny,to,watch,the,locals,blindly,point,the,finger,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,and,from,hell's,ending,had,me,whistling,the,stonecutters,song,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,don't,worry,-,it'll,all,make,sense,when,you,see,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,now,onto,from,hell's,appearance,:,it's,certainly,dark,and,...,hollow,2,),.,NaN,NaN,NaN,NaN,NaN,NaN
17,oscar,winner,martin,childs',(,shakespeare,in,love,),production,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,even,the,acting,in,from,hell,is,solid,",",with,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,ians,holm,(,joe,gould's,secret,),and,richardson,(,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,i,cringed,the,first,time,she,opened,her,mouth,",",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,the,film,",",however,",",is,all,good,.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2,:,00,-,r,for,strong,violence/gore,",",sexuality,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
count = df['films'].value_counts() 
print(count)

the          3
it's         2
i            2
in           2
to           1
even         1
when         1
ians         1
for          1
if           1
now          1
and          1
oscar        1
don't        1
getting      1
upon         1
abberline    1
2            1
Name: films, dtype: int64